version: 2.1

commands:
  test-nodejs:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Test
          command: npm run test

jobs:
  node-v8:
    docker:
      - image: node:8
    working_directory: ~/repo
    steps:
      - test-nodejs
  node-v9:
    docker:
      - image: node:9
    working_directory: ~/repo
    steps:
      - test-nodejs
  node-v10:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v6
      - node-v8
      - node-v10
